### ISSUE TITLE
montana zip not working

### ISSUE THREAD

**Issue by pinhead001** [mchat/call-my-congress#26]
I tried looking up rep on https://www.callmycongress.com/ using my zip code - 59937, and several other Montana zip codes including the state captial, Helena (59601) and received the following message...

District number provided does not exist in your state.

I tried it for a Washington state zip and it did work...

https://www.callmycongress.com/WA-2

I am not familiar with the code that callmycongress uses, but did a little looking and found that one of the sites listed at the bottom of the page is whoismyrepresentative.com. I tried the montana zips using the PHP syntax from following page and got no results... http://www.whoismyrepresentative.com/api
Using the zip code lookup on the following page was successful: http://whoismyrepresentative.com/ 
It returned the following web page: http://whoismyrepresentative.com/search/zip/59937 with the correct reps.

Not sure if any of this is relevant or helpful. Just thought I would let you know that the site is not fully functional.

**Comment by mchat** [comment]
Thank you for the detailed information! Apologies for my slow response — haven't had much time to look into this recently.

I just discovered that whoismyrepresentative.com seems to be down completely, so I've actually removed the ability to do a zip-only lookup entirely for now as I don't have a replacement API in mind.

I was able to successfully lookup the Montana at large district using a street address in Montana, but got the same error you did about invalid district numbers. It looks like this was caused because the representative seat in MT is still listed as vacant (should be updated soon). I just merged #28 which should fix this, and just show the data it does have (the senators).

Feel free to reopen this issue if you see any other errors moving forward!
